# Generated by Django 3.0.4 on 2022-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Emp_Name', models.CharField(max_length=25)),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
